spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  data:
    mongodb:
      username: cloudbooklibrary
      host: ds137550.mlab.com
      password: 1a2s3d$F%G^H
      port: 37550
      database: booklibrary