spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  data:
    mongodb:
      username: cloudbooklibrary
      host: 10.141.4.72
      password: 1a2s3d$F%G^H
      port: 27207
      database: booklibrary